apiVersion: v1
kind: Secret
metadata:
    name: demo-db
    namespace: demo
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:CIeaNDYm8fs=,iv:Rmu/7tVH8t3sL51U4V1yMfCfViDXjuGIKtkRvawt3S8=,tag:pMPE78gYNE4NdPswKhu3nA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:lcGFRHUzthjp4TGZ0INgWX7zoGf+Sg==,iv:5yrWn8ZWc1Ual8N/JfMTUs7C5tPWEpBS/P1r/DpY0I4=,tag:ZhvxPldIGX66QxMTqelCYQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:GvLlqPH9h7o8PqpK/q5vycxVgV59ENvUXoOWMkA/6Q==,iv:HUUBUz5L1NK80VzSMfmTQsrniBD5X8tLxCpBJ56HaAI=,tag:LTzFw11HDmQtvTIivcy+LA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:jw1OkgrS1kc=,iv:BPqV4FGa8StW0yuMpxPQlYJyhp1CrT46iPm/ls8pZes=,tag:6okx+5jsYK69IwXUv0UoGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtLzdXMlZhWjA0YmtKOXpD
            YlpadlI3Qmg2Q0JFeEZQbkJGZkNTS3ROc3hBCitkcnAyZUJaRzJrZUNTaEExSzZl
            QkxGeUpNT09jMWdWbGdhbVdKNkxJd3MKLS0tIGlUL29QNU9XL01Ec01xYTdaVVlJ
            WWVCdDlMcmx1YTgvMVN4NGJnOTVZTlEKxvNcJ865FzESIUWCAnuq9TC2lPs3D+7j
            f9FzjgB5axXyba3+ql9HANWoxUszuEoSaNnPDuiHh3TwtyCFMGqaRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tvhktpsgu2p8h9rl4cmyyhf0x866cu27uxxx9javr43vxqnh492slrj5rr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T10:37:52Z"
    mac: ENC[AES256_GCM,data:FtkKxB83HOOIrerrkfGAndTzuX5KNTgnBEDczV4vflcXbNXiH0EbJo8cwtrizWJ1BYP5sa/NmodFQHZ56MIvqLoRGbDwWCHOXsWUbPf+rqvIBhdeq/0GTI0IUQXfhmEUUP5bXskEz9Eh3wrgXziqUAHSs9UaERIHrxKeSwG4Q8s=,iv:Cu9J2wnWpVukk3uF4w+Ef+b+/cOQgUlc/kRZd5KmxJA=,tag:BkKEmONRElX7YedxKTdX3A==,type:str]
    version: 3.13.3
