apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
namespace: podinfo-dev
configMapGenerator:
  - name: podinfo-values
    namespace: podinfo-dev
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
  immutable: true