image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: "6.14.1"
replicaCount: 1
logLevel: debug
ui:
  message: "Hello from GitOps - DEV"
  color: "#34495e"
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  seccompProfile:
    type: RuntimeDefault
